corruption:
  - gaussian_noise
  - shot_noise
  - impulse_noise
  - defocus_blur
  - glass_blur
  - motion_blur
  - zoom_blur
  - snow
  - frost
  - fog
  - brightness
  - contrast
  - elastic_transform
  - pixelate
  - jpeg_compression
open_set:     [true, false]
csood_source: [svhn_c, rome32]
seed:         [0]
